"""Add game_user Association Table

Revision ID: 144752fe7dcd
Revises: bbbc396efcad
Create Date: 2023-12-07 12:33:57.077408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144752fe7dcd'
down_revision = 'bbbc396efcad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_user')
    with op.batch_alter_table('game_users', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_game_id_games'), 'games', ['game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_game_id_games'), type_='foreignkey')
        batch_op.drop_column('game_id')

    with op.batch_alter_table('game_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('game_user',
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='fk_game_user_game_id_games'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_game_user_user_id_users'),
    sa.PrimaryKeyConstraint('game_id', 'user_id')
    )
    # ### end Alembic commands ###
